---
title: "Regression and Chi Square"
author: "Brian Wright"
date: "February 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE}
#load package vcd 
library(vcd)
str(Arthritis)
#We can see from the summary that we have several factor (categorical) level and one ordered factor (ordinal) 
# So if we want to run a test of indendence and Chi Square is perfect, 
#Trying to determine if Treatment and Improved are independent 
#We will set the signifance level at .05 and generate a test statistic
chisq.test(Arthritis$Treatment,Arthritis$Improved)
# Results show us that p value is less than .05 meaning are test is significant
#You can also create a table first, some people like to do this because it makes certain steps more visable, such percentages in the categories and totals
tbl <- table(Arthritis$Treatment, Arthritis$Improved)
#The results should be the same. 
chisq.test(tbl)
```
Regression
```{r, echo=TRUE}
#For this example we are going to use data from the faraway library from the package with the same name.
library(faraway)
#The data set is stat500, so let's take a look
?stat500
str(stat500)
#Determine whether midterm and homework grades predict the final
x <- lm(final~midterm+hw,stat500)
summary(x)


```

